export const bufferByRoadClass = new Map([
  ['primary', 14],
  ['primary_link', 14],
  ['secondary', 14],
  ['secondary_link', 14],
  ['tertiary', 14],
  ['tertiary_link', 14],
  ['unclassified', 10],
  ['residential', 10],
  ['living_street', 10],
  ['pedestrian', 10],
  ['road', 10],
  ['cycleway', 7],
  ['path', 7],
  ['footway', 7],
  ['track', 10],
  ['service', 10],
  ['construction', 10],
])
